format = """
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$character"""

[character]
success_symbol = '[  ](bold green)'
error_symbol = '[  ](bold red)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "󰉓  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"src" = " "
"lib" = " "

[git_branch]
symbol = "󰘬 "
style = "bg:#394260"
format = '[[ $symbol$branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind)](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
