#pragma once

#define VIAL_KEYBOARD_UID {0x6B, 0xA3, 0xEB, 0x3B, 0x38, 0x35, 0x55, 0x52}

// 分割のための設定
#define USE_SERIAL
#define SPLIT_USB_DETECT

// LEDインジケーター
#define LED_CAPS_LOCK_PIN C7

// RGBライト
#define WS2812_DI_PIN B7
#define RGBLIGHT_LED_COUNT 87
#define RGBLIGHT_LED_SPLIT {37, 50}
#define RGBLIGHT_SLEEP
#define RGBLIGHT_TIMEOUT 300000  // 5 min
#define RGBLIGHT_SPLIT
#define RGBLIGHT_DEFAULT_ON false

// アニメーションを個別に無効化
#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE

// MIDI
#define MIDI_ADVANCED

// 不要な機能を無効化
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING
#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT
